# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userpic', models.ImageField(blank=True, null=True, upload_to='UserProfile_Pic')),
                ('dateofbirth', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('levelofeducation', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('nationality', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
