# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='UserProfile_Pic', verbose_name='<django.db.models.fields.related.OneToOneField><built-in function id>'),
        ),
    ]
