# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_donate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donate',
            new_name='UserDonateMoMo',
        ),
    ]
