# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20170703_1928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDonateMoMo',
            new_name='UserDonateMoMo1',
        ),
    ]
