# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20170703_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDonateMoMo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=999)),
                ('comment', models.TextField()),
                ('transactionId', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserDonateMoMo1',
        ),
    ]
