# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 09:32
from __future__ import unicode_literals

import Concours.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=100)),
                ('schoollogo', models.ImageField(upload_to=Concours.models.Concour.concour_directory_path)),
                ('schooldescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConcourChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapternumber', models.IntegerField()),
                ('chaptertitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConcourCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('courselogo', models.ImageField(upload_to=Concours.models.ConcourCourse.course_logo_directory_path)),
                ('courseintrovideo', models.FileField(null=True, upload_to=Concours.models.ConcourCourse.course_videintro_directory_path)),
                ('coursevideoposter', models.FileField(blank=True, null=True, upload_to=Concours.models.ConcourCourse.course_videoposter_directory_path)),
                ('courseintro', models.TextField()),
                ('coursestart', models.DateField(null=True)),
                ('courseend', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConcourDepartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConcourForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('timecreated', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourChapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourCourse')),
            ],
            options={
                'ordering': ['-timecreated'],
            },
        ),
        migrations.CreateModel(
            name='ConcourMCQAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=999)),
                ('correctanswer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConcourMCQQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_marks', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourChapter')),
            ],
        ),
        migrations.CreateModel(
            name='ConcourMCQScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourChapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConcourReplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_reply', models.TextField()),
                ('replystate', models.BooleanField(default=False)),
                ('timecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourForum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timecreated'],
            },
        ),
        migrations.CreateModel(
            name='ConcourTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=100)),
                ('teacheremail', models.CharField(max_length=100)),
                ('teachercontact', models.CharField(max_length=100)),
                ('teacherpic', models.ImageField(upload_to=Concours.models.ConcourTeacher.teacher_directory_path)),
                ('teacherbiography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConcourToCourseMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourCourse')),
                ('schoolname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.Concour')),
            ],
        ),
        migrations.CreateModel(
            name='ConcourTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicnumber', models.IntegerField()),
                ('topicname', models.CharField(max_length=100)),
                ('topicintro', models.TextField(blank=True, null=True)),
                ('topicvideo', models.FileField(blank=True, null=True, upload_to=Concours.models.ConcourTopic.topic_video_directory_path)),
                ('topicdocument', models.FileField(blank=True, null=True, upload_to=Concours.models.ConcourTopic.topic_document_directory_path)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourChapter')),
            ],
        ),
        migrations.CreateModel(
            name='ConcourUserForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('timecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourCourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timecreated'],
            },
        ),
        migrations.CreateModel(
            name='ConcourUserForumReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usercomment_reply', models.TextField()),
                ('replystate', models.BooleanField(default=False)),
                ('timecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usercomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourUserForum')),
            ],
            options={
                'ordering': ['-timecreated'],
            },
        ),
        migrations.CreateModel(
            name='MoMoTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('transactionId', models.IntegerField()),
                ('statusCode', models.IntegerField()),
                ('timecreated', models.DateTimeField(auto_now_add=True)),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourToCourseMap')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timecreated'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubscribedConcourcourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('concour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.Concour')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourCourse')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourDepartement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timecreated'],
            },
        ),
        migrations.AddField(
            model_name='concourmcqanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourMCQQuestion'),
        ),
        migrations.AddField(
            model_name='concourforum',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourTopic'),
        ),
        migrations.AddField(
            model_name='concourforum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concourcourse',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourDepartement'),
        ),
        migrations.AddField(
            model_name='concourchapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourCourse'),
        ),
        migrations.AddField(
            model_name='concourchapter',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourTeacher'),
        ),
        migrations.AddField(
            model_name='concour',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concours.ConcourDepartement'),
        ),
    ]
